### ISSUE TITLE
Pictures don't scale

### ISSUE THREAD

**Issue by gardncol** [MatthK/swfd#2]
On the index page, the pictures break out past the bounds of the top news card and the article previews. On the article page, pictures get cut off by the side bar (not ideal, but preferred to going under side bar content). Is there a way to scale the images so they fit into the bounds of the article? Link to screenshots https://imgur.com/a/syde6sC

As an aside, this is a really cool project thank you for building it.

**Comment by MatthK** [comment]
I guess I wasn't very consistent with the CSS here. The optional tag "overflow-hidden" in the <div> will cut-off the images that are too big.

In my feeds that happens rarely enough, so it never bothered me. And on the article page, you can side scroll to see the full photo.

I was wondering as well if there's an easy way to scale the images, but I guess it would have to be done in the "content". And I'm not sure that there would be an easy search/replace on all <img> tags possible.

**Comment by MatthK** [comment]
I made the changes in the Selfoss-Webfront repository. However, I first have to figure out again how to create the docker image and update it on the docker site.

**Comment by gardncol** [comment]
Great! Thank you. No rush from me. I definetly didn't expect this issue to be addressed so quickly. I'll keep my eyes out for the update.

**Comment by MatthK** [comment]
The docker image should be updated now (at least that's what I believe).

**Comment by gardncol** [comment]
I updated, and the cut off is working as expected. Thank you again.
